# Generated by Django 5.2.4 on 2025-08-06 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, help_text="세션 제목", max_length=200)),
                ("instruction", models.TextField(help_text="시스템 프롬프트 (SimpleChatConfig의 instruction)")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "model",
                    models.CharField(
                        choices=[("gpt-4o", "gpt-4o"), ("gpt-4o-mini", "gpt-4o-mini")],
                        default=[("gpt-4o", "gpt-4o"), ("gpt-4o-mini", "gpt-4o-mini")],
                        help_text="사용할 OpenAI AI 모델",
                        max_length=50,
                    ),
                ),
                ("temperature", models.FloatField(default=1.0, help_text="응답의 창의성 정도 (0.0~2.0)")),
                ("max_tokens", models.IntegerField(default=1000, help_text="최대 응답 토큰 수")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "채팅 세션",
                "verbose_name_plural": "채팅 세션들",
                "ordering": ["-pk"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant"), ("system", "System")], max_length=20
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_set",
                        to="roleplay.chatsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "채팅 메시지",
                "verbose_name_plural": "채팅 메시지들",
                "ordering": ["pk"],
            },
        ),
    ]
