# Generated by Django 5.2.4 on 2025-08-06 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant"), ("system", "System")], max_length=20
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("input_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("output_tokens", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"model__in": ("generalchatsession", "roleplaychatsession")},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "채팅 메시지",
                "verbose_name_plural": "채팅 메시지들",
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(fields=["content_type", "object_id"], name="roleplay_ch_content_7bc0b5_idx"),
                    models.Index(fields=["created_at"], name="roleplay_ch_created_468f6c_idx"),
                    models.Index(fields=["role", "created_at"], name="roleplay_ch_role_edc5c0_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="GeneralChatSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, help_text="세션 제목", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("system_prompt", models.TextField(blank=True, help_text="실제 사용된 시스템 프롬프트")),
                ("model", models.CharField(default="gpt-4o", help_text="사용할 AI 모델", max_length=50)),
                ("temperature", models.FloatField(default=1.0, help_text="응답의 창의성 정도 (0.0~2.0)")),
                ("max_tokens", models.IntegerField(default=1000, help_text="최대 응답 토큰 수")),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("general", "일반 대화"),
                            ("qa", "질문/답변"),
                            ("customer_support", "고객 지원"),
                            ("education", "교육"),
                            ("other", "기타"),
                        ],
                        default="general",
                        help_text="채팅 목적",
                        max_length=50,
                    ),
                ),
                ("context", models.TextField(blank=True, help_text="추가 컨텍스트 정보")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "일반 채팅 세션",
                "verbose_name_plural": "일반 채팅 세션들",
                "indexes": [
                    models.Index(fields=["user", "created_at"], name="roleplay_ge_user_id_0e2b88_idx"),
                    models.Index(fields=["purpose", "created_at"], name="roleplay_ge_purpose_6508d7_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RolePlayChatSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, help_text="세션 제목", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("system_prompt", models.TextField(blank=True, help_text="실제 사용된 시스템 프롬프트")),
                ("model", models.CharField(default="gpt-4o", help_text="사용할 AI 모델", max_length=50)),
                ("temperature", models.FloatField(default=1.0, help_text="응답의 창의성 정도 (0.0~2.0)")),
                ("max_tokens", models.IntegerField(default=1000, help_text="최대 응답 토큰 수")),
                ("prompt_name", models.CharField(help_text="프롬프트 이름", max_length=100)),
                ("language", models.CharField(help_text="학습 언어", max_length=50)),
                ("user_role", models.CharField(help_text="사용자 역할", max_length=200)),
                ("gpt_role", models.CharField(help_text="AI 역할", max_length=200)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("beginner", "Beginner"), ("intermediate", "Intermediate"), ("advanced", "Advanced")],
                        default="beginner",
                        help_text="난이도",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "역할극 채팅 세션",
                "verbose_name_plural": "역할극 채팅 세션들",
                "indexes": [
                    models.Index(fields=["user", "created_at"], name="roleplay_ro_user_id_fe04cf_idx"),
                    models.Index(fields=["language", "difficulty"], name="roleplay_ro_languag_699c6d_idx"),
                ],
            },
        ),
    ]
