# Generated by Django 5.2.4 on 2025-08-06 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roleplay", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatmessage",
            options={"ordering": ["pk"], "verbose_name": "채팅 메시지", "verbose_name_plural": "채팅 메시지들"},
        ),
        migrations.AlterModelOptions(
            name="chatsession",
            options={"ordering": ["-pk"], "verbose_name": "채팅 세션", "verbose_name_plural": "채팅 세션들"},
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="token_count",
        ),
        migrations.RemoveField(
            model_name="chatsession",
            name="total_tokens",
        ),
    ]
