# Generated by Django 5.2.4 on 2025-08-06 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roleplay", "0002_alter_chatmessage_options_alter_chatsession_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="message_set", to="roleplay.chatsession"
            ),
        ),
    ]
