# Generated by Django 5.2.4 on 2025-08-06 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roleplay", "0002_remove_chatsession_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatsession",
            name="max_tokens",
            field=models.IntegerField(
                default=1000,
                help_text="최대 응답 토큰 수 (1~4096)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4096),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="temperature",
            field=models.FloatField(
                default=1.0,
                help_text="응답의 창의성 정도 (0.0~2.0)",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(2.0),
                ],
            ),
        ),
    ]
