# Generated by Django 5.2.4 on 2025-08-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roleplay", "0003_alter_chatsession_max_tokens_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatsession",
            name="model",
            field=models.CharField(
                choices=[("gpt-4o", "gpt-4o"), ("gpt-4o-mini", "gpt-4o-mini")],
                default="gpt-4o-mini",
                help_text="사용할 OpenAI AI 모델",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="title",
            field=models.CharField(help_text="세션 제목", max_length=200),
        ),
    ]
