# Generated by Django 5.2.4 on 2025-08-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prompt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("content", models.TextField(verbose_name="프롬프트 내용")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("writing", "글쓰기"),
                            ("coding", "코딩"),
                            ("analysis", "분석"),
                            ("creative", "창작"),
                            ("business", "비즈니스"),
                            ("education", "교육"),
                            ("other", "기타"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="카테고리",
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list, verbose_name="태그")),
                ("usage_count", models.IntegerField(default=0, verbose_name="사용 횟수")),
                ("is_favorite", models.BooleanField(default=False, verbose_name="즐겨찾기")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
            ],
            options={
                "verbose_name": "프롬프트",
                "verbose_name_plural": "프롬프트",
                "ordering": ["-is_favorite", "-usage_count", "-created_at"],
            },
        ),
    ]
