# Generated by Django 5.2.4 on 2025-08-11 03:23

import django.core.validators
import prompts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prompt",
            name="content",
            field=models.TextField(
                help_text="최소 50자, [변수명] 형식으로 변수 사용 가능",
                validators=[
                    django.core.validators.MinLengthValidator(
                        50, message="프롬프트 내용은 최소 50자 이상이어야 합니다."
                    ),
                    prompts.validators.validate_prompt_variables,
                ],
                verbose_name="프롬프트 내용",
            ),
        ),
        migrations.AlterField(
            model_name="prompt",
            name="tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="최대 10개, 각 태그 2-20자",
                validators=[prompts.validators.validate_tags_list],
                verbose_name="태그",
            ),
        ),
        migrations.AlterField(
            model_name="prompt",
            name="title",
            field=models.CharField(
                help_text="5-200자, 특수문자 제한",
                max_length=200,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(5, message="제목은 최소 5자 이상이어야 합니다."),
                    django.core.validators.MaxLengthValidator(200, message="제목은 200자를 초과할 수 없습니다."),
                    prompts.validators.validate_no_special_chars,
                ],
                verbose_name="제목",
            ),
        ),
    ]
