# Generated by Django 5.2.4 on 2025-08-11 05:33

import django.core.validators
import prompts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0002_alter_prompt_content_alter_prompt_tags_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prompt",
            name="title",
            field=models.CharField(
                help_text="5-200자, 특수문자 제한",
                max_length=200,
                validators=[
                    django.core.validators.MinLengthValidator(5, message="제목은 최소 5자 이상이어야 합니다."),
                    django.core.validators.MaxLengthValidator(200, message="제목은 200자를 초과할 수 없습니다."),
                    prompts.validators.validate_no_special_chars,
                ],
                verbose_name="제목",
            ),
        ),
    ]
