# Generated by Django 5.2.4 on 2025-08-11 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.BigIntegerField(unique=True)),
                ("name", models.CharField(max_length=300)),
                ("cover_image_url", models.URLField(blank=True, max_length=500)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.BigIntegerField(unique=True)),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.BigIntegerField(unique=True)),
                ("rank", models.IntegerField()),
                ("title", models.CharField(max_length=300)),
                ("lyrics", models.TextField(blank=True)),
                ("genre", models.JSONField(default=list)),
                ("release_date", models.DateField()),
                ("likes", models.IntegerField(default=0)),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="songs", to="melon.album"
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="songs", to="melon.artist"
                    ),
                ),
            ],
            options={
                "ordering": ["rank"],
            },
        ),
    ]
