# Generated by Django 5.2.4 on 2025-08-12 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("widgets", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WeatherLocation",
        ),
    ]
